coverage:
  precision: 2
  round: down
  range: "35...100"
  status:
    project:
      default:
        informational: true
    patch: off
fixes:
  - "ros_ws/src/*/rmf_utils/::"
comment:
  layout: "diff, flags, files"
  behavior: default
ignore:
  - "rmf_utils/include/rmf_utils/catch.hpp"
